import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";

const poppins = Poppins({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-Poppins',
});

export const metadata: Metadata = {
  title: "Forum-Issues",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <Theme appearance="light" accentColor="amber">
          <NavBar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
